# Usa la imagen base de OpenJDK 21
FROM hackyo/maven:3.9-jdk-21 AS builder

# Establece el directorio de trabajo
WORKDIR /app

# Copiar los archivos necesarios para compilar
COPY pom.xml ./
COPY src ./src

# Ejecutar las pruebas unitarias
RUN mvn clean test

# Usa una imagen más liviana para ejecutar las pruebas (opcional)
FROM openjdk:21-jdk-slim

# Copia el código y las dependencias necesarias para las pruebas
COPY --from=builder /app /app

# Establece el directorio de trabajo
WORKDIR /app

# Ejecuta las pruebas
CMD ["mvn", "test"]
